### PR TITLE
Create IT-PRO-Portugal-24-Mobile-Powers-Edition.md

### PR DESCRIPTION
**Pull request by rramoscabral**

### CODE REVIEW

**Comment by cmota** [comment]
Hello @rramoscabral! 

I noticed that you've got two PR's for the same event right? It only differs on the date.

You should create a single one with the start date 2020-07-07 and end date 2020-07-08.

```
date_start: 2020-07-08
date_end:   2020-07-08
```

Thank you for your contribution! 🙌

**Comment by rramoscabral** [comment]
My mistake :(

**Comment by cmota** [comment]
No problen @rramoscabral 🙂.

Can you update your PR with the new date and close the other one so I can accept it, please?

**Comment by cmota** [comment]
I've updated the file to the suggested time. Accepting it 🙂

**Pull request merged**
