### PR TITLE
Add PiHackaton & LandingFestival

### PR DESCRIPTION
**Pull request by OldMetalmind**
Add πHackaton information in Coimbra.

### CODE REVIEW

**Comment by cmota** [comment]
A really small thing, but @OldMetalmind could you use a hyphen to separate words instead of underscore?

Sorry, but it's to keep consistency 😇

Thank you! 🙂

**Comment by OldMetalmind** [comment]
No problem. I'll update it.

**Comment by OldMetalmind** [comment]
@cmota files renamed accordingly to the convention.

**Comment by cmota** [comment]
Sorry, but you missed the pi hackathon @OldMetalmind 😇

**Comment by OldMetalmind** [comment]
🤦 ups my bad, done.

**Comment by cmota** [comment]
All good! Going to accept it 🙂

**Pull request merged**
